"""Crypto simulation trading sub-module (spot + USDT-M perpetual)."""
from .api import (
    list_symbols,
    get_quotes,
    get_kline,
    get_rules,
    get_contract_rules,
    get_account,
    create_account,
    delete_account,
    get_positions,
    buy,
    sell,
    contract_open,
    contract_close,
    get_contract_positions,
    get_orders,
    get_balance_log,
    main,
)

__all__ = [
    "list_symbols",
    "get_quotes",
    "get_kline",
    "get_rules",
    "get_contract_rules",
    "get_account",
    "create_account",
    "delete_account",
    "get_positions",
    "buy",
    "sell",
    "contract_open",
    "contract_close",
    "get_contract_positions",
    "get_orders",
    "get_balance_log",
    "main",
]
